[workspace]
resolver = "2"
members = [
    "crates/zero-core",
    "crates/zero-bus",
    "crates/zero-motion",
    "crates/zero-hal",
    "crates/zero-dsp",
    "crates/zero-modbus",
    "crates/zero-ipc",
    "crates/zero-vision",
    "crates/zero-ethercat",
    "crates/zero-dynamics",
    "crates/zero-plc",
    "crates/zero-dds",
    "crates/zero-tinyai",
    "crates/zero-sys",
    "crates/zero-fastcgi",
    "crates/zero-caddy",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Phong Vo <phong.vo@zerouniverse.io>", "ZeroUniverse Team"]
license = "MIT"
repository = "https://github.com/kzxl/ZeroRust"
homepage = "https://github.com/kzxl/ZeroRust"
keywords = ["industrial-automation", "robotics", "real-time", "canopen", "motion-control"]
categories = ["embedded", "hardware-support", "science::robotics", "no-std"]
readme = "README.md"
