[package]
name = "zero-vfs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Sovereign Virtual File System and Security Sandbox for web hosting panels & embedded controllers in ZeroRust"
readme = "README.md"
keywords = ["vfs", "sandbox", "path-traversal", "jail", "zpanl"]
categories.workspace = true

[features]
default = ["std"]
std = ["zero-core/std"]

[dependencies]
zero-core = { path = "../zero-core", default-features = false }
